### ISSUE TITLE
pipelayer 0.1.0 fails to load with Factorissimo2 2.2.3

### ISSUE THREAD

**Issue by WonderDog** [mspielberg/factorio-pipelayer#1]
Start up error when pipelayer 0.1.0 loaded with Factorissimo2 2.2.3

`Error ModManager.cpp:1024: Failed to load mod "pipelayer": __pipelayer__/data-updates.lua:1: __pipelayer__/prototypes/bpproxies.lua:25: attempt to index field 'minable' (a nil value)`

[Log file of only Pipelayer & Facorissimo](https://pastebin.com/pXAf5PNy)

**Comment by mspielberg** [comment]
Thanks for the report! Fixed in v0.1.1.
